[build]
  publish = "public"        # map met index.html
  # geen build command nodig voor pure HTML/JS

[functions]
  directory = "netlify/functions"
  included_files = ["knowledge/**"]   # neem knowledge-map mee in bundle

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
