[build]
  publish = "public"        # map met index.html

[functions]
  directory = "netlify/functions"
  included_files = ["knowledge/**"]   # neem de hele knowledge-map mee in de bundle

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
